package com.example.mybatisgenerator.model;

import java.io.Serializable;
import java.util.Date;

public class ActRuExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.BUSINESS_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String businessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.PARENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.SUPER_EXEC_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String superExec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String rootProcInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.ACT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_ACTIVE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_CONCURRENT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isConcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_EVENT_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isEventScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_MI_ROOT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isMiRoot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.CACHED_ENT_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer cachedEntState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.START_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.START_USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String startUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Date lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.IS_COUNT_ENABLED_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte isCountEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.EVT_SUBSCR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer evtSubscrCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.TASK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer taskCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer jobCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.TIMER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer timerJobCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.SUSP_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer suspJobCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.DEADLETTER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer deadletterJobCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.VAR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer varCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_EXECUTION.ID_LINK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer idLinkCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.ID_
     *
     * @return the value of ACT_RU_EXECUTION.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.ID_
     *
     * @param id the value for ACT_RU_EXECUTION.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.REV_
     *
     * @return the value of ACT_RU_EXECUTION.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.REV_
     *
     * @param rev the value for ACT_RU_EXECUTION.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.PROC_INST_ID_
     *
     * @return the value of ACT_RU_EXECUTION.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.PROC_INST_ID_
     *
     * @param procInstId the value for ACT_RU_EXECUTION.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.BUSINESS_KEY_
     *
     * @return the value of ACT_RU_EXECUTION.BUSINESS_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.BUSINESS_KEY_
     *
     * @param businessKey the value for ACT_RU_EXECUTION.BUSINESS_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.PARENT_ID_
     *
     * @return the value of ACT_RU_EXECUTION.PARENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.PARENT_ID_
     *
     * @param parentId the value for ACT_RU_EXECUTION.PARENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.PROC_DEF_ID_
     *
     * @return the value of ACT_RU_EXECUTION.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.PROC_DEF_ID_
     *
     * @param procDefId the value for ACT_RU_EXECUTION.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.SUPER_EXEC_
     *
     * @return the value of ACT_RU_EXECUTION.SUPER_EXEC_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getSuperExec() {
        return superExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.SUPER_EXEC_
     *
     * @param superExec the value for ACT_RU_EXECUTION.SUPER_EXEC_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setSuperExec(String superExec) {
        this.superExec = superExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.ROOT_PROC_INST_ID_
     *
     * @return the value of ACT_RU_EXECUTION.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getRootProcInstId() {
        return rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.ROOT_PROC_INST_ID_
     *
     * @param rootProcInstId the value for ACT_RU_EXECUTION.ROOT_PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setRootProcInstId(String rootProcInstId) {
        this.rootProcInstId = rootProcInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.ACT_ID_
     *
     * @return the value of ACT_RU_EXECUTION.ACT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.ACT_ID_
     *
     * @param actId the value for ACT_RU_EXECUTION.ACT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setActId(String actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_ACTIVE_
     *
     * @return the value of ACT_RU_EXECUTION.IS_ACTIVE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_ACTIVE_
     *
     * @param isActive the value for ACT_RU_EXECUTION.IS_ACTIVE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_CONCURRENT_
     *
     * @return the value of ACT_RU_EXECUTION.IS_CONCURRENT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_CONCURRENT_
     *
     * @param isConcurrent the value for ACT_RU_EXECUTION.IS_CONCURRENT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsConcurrent(Byte isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_SCOPE_
     *
     * @return the value of ACT_RU_EXECUTION.IS_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsScope() {
        return isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_SCOPE_
     *
     * @param isScope the value for ACT_RU_EXECUTION.IS_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsScope(Byte isScope) {
        this.isScope = isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_EVENT_SCOPE_
     *
     * @return the value of ACT_RU_EXECUTION.IS_EVENT_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsEventScope() {
        return isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_EVENT_SCOPE_
     *
     * @param isEventScope the value for ACT_RU_EXECUTION.IS_EVENT_SCOPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsEventScope(Byte isEventScope) {
        this.isEventScope = isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_MI_ROOT_
     *
     * @return the value of ACT_RU_EXECUTION.IS_MI_ROOT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsMiRoot() {
        return isMiRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_MI_ROOT_
     *
     * @param isMiRoot the value for ACT_RU_EXECUTION.IS_MI_ROOT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsMiRoot(Byte isMiRoot) {
        this.isMiRoot = isMiRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.SUSPENSION_STATE_
     *
     * @return the value of ACT_RU_EXECUTION.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.SUSPENSION_STATE_
     *
     * @param suspensionState the value for ACT_RU_EXECUTION.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.CACHED_ENT_STATE_
     *
     * @return the value of ACT_RU_EXECUTION.CACHED_ENT_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getCachedEntState() {
        return cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.CACHED_ENT_STATE_
     *
     * @param cachedEntState the value for ACT_RU_EXECUTION.CACHED_ENT_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setCachedEntState(Integer cachedEntState) {
        this.cachedEntState = cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.TENANT_ID_
     *
     * @return the value of ACT_RU_EXECUTION.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.TENANT_ID_
     *
     * @param tenantId the value for ACT_RU_EXECUTION.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.NAME_
     *
     * @return the value of ACT_RU_EXECUTION.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.NAME_
     *
     * @param name the value for ACT_RU_EXECUTION.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.START_TIME_
     *
     * @return the value of ACT_RU_EXECUTION.START_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.START_TIME_
     *
     * @param startTime the value for ACT_RU_EXECUTION.START_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.START_USER_ID_
     *
     * @return the value of ACT_RU_EXECUTION.START_USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getStartUserId() {
        return startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.START_USER_ID_
     *
     * @param startUserId the value for ACT_RU_EXECUTION.START_USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setStartUserId(String startUserId) {
        this.startUserId = startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.LOCK_TIME_
     *
     * @return the value of ACT_RU_EXECUTION.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.LOCK_TIME_
     *
     * @param lockTime the value for ACT_RU_EXECUTION.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.IS_COUNT_ENABLED_
     *
     * @return the value of ACT_RU_EXECUTION.IS_COUNT_ENABLED_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getIsCountEnabled() {
        return isCountEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.IS_COUNT_ENABLED_
     *
     * @param isCountEnabled the value for ACT_RU_EXECUTION.IS_COUNT_ENABLED_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIsCountEnabled(Byte isCountEnabled) {
        this.isCountEnabled = isCountEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.EVT_SUBSCR_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.EVT_SUBSCR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getEvtSubscrCount() {
        return evtSubscrCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.EVT_SUBSCR_COUNT_
     *
     * @param evtSubscrCount the value for ACT_RU_EXECUTION.EVT_SUBSCR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setEvtSubscrCount(Integer evtSubscrCount) {
        this.evtSubscrCount = evtSubscrCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.TASK_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.TASK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getTaskCount() {
        return taskCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.TASK_COUNT_
     *
     * @param taskCount the value for ACT_RU_EXECUTION.TASK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTaskCount(Integer taskCount) {
        this.taskCount = taskCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.JOB_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getJobCount() {
        return jobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.JOB_COUNT_
     *
     * @param jobCount the value for ACT_RU_EXECUTION.JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setJobCount(Integer jobCount) {
        this.jobCount = jobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.TIMER_JOB_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.TIMER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getTimerJobCount() {
        return timerJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.TIMER_JOB_COUNT_
     *
     * @param timerJobCount the value for ACT_RU_EXECUTION.TIMER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTimerJobCount(Integer timerJobCount) {
        this.timerJobCount = timerJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.SUSP_JOB_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.SUSP_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getSuspJobCount() {
        return suspJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.SUSP_JOB_COUNT_
     *
     * @param suspJobCount the value for ACT_RU_EXECUTION.SUSP_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setSuspJobCount(Integer suspJobCount) {
        this.suspJobCount = suspJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.DEADLETTER_JOB_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.DEADLETTER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getDeadletterJobCount() {
        return deadletterJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.DEADLETTER_JOB_COUNT_
     *
     * @param deadletterJobCount the value for ACT_RU_EXECUTION.DEADLETTER_JOB_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setDeadletterJobCount(Integer deadletterJobCount) {
        this.deadletterJobCount = deadletterJobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.VAR_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.VAR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getVarCount() {
        return varCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.VAR_COUNT_
     *
     * @param varCount the value for ACT_RU_EXECUTION.VAR_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setVarCount(Integer varCount) {
        this.varCount = varCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_EXECUTION.ID_LINK_COUNT_
     *
     * @return the value of ACT_RU_EXECUTION.ID_LINK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getIdLinkCount() {
        return idLinkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_EXECUTION.ID_LINK_COUNT_
     *
     * @param idLinkCount the value for ACT_RU_EXECUTION.ID_LINK_COUNT_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setIdLinkCount(Integer idLinkCount) {
        this.idLinkCount = idLinkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", businessKey=").append(businessKey);
        sb.append(", parentId=").append(parentId);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", superExec=").append(superExec);
        sb.append(", rootProcInstId=").append(rootProcInstId);
        sb.append(", actId=").append(actId);
        sb.append(", isActive=").append(isActive);
        sb.append(", isConcurrent=").append(isConcurrent);
        sb.append(", isScope=").append(isScope);
        sb.append(", isEventScope=").append(isEventScope);
        sb.append(", isMiRoot=").append(isMiRoot);
        sb.append(", suspensionState=").append(suspensionState);
        sb.append(", cachedEntState=").append(cachedEntState);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", name=").append(name);
        sb.append(", startTime=").append(startTime);
        sb.append(", startUserId=").append(startUserId);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", isCountEnabled=").append(isCountEnabled);
        sb.append(", evtSubscrCount=").append(evtSubscrCount);
        sb.append(", taskCount=").append(taskCount);
        sb.append(", jobCount=").append(jobCount);
        sb.append(", timerJobCount=").append(timerJobCount);
        sb.append(", suspJobCount=").append(suspJobCount);
        sb.append(", deadletterJobCount=").append(deadletterJobCount);
        sb.append(", varCount=").append(varCount);
        sb.append(", idLinkCount=").append(idLinkCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}