package com.example.mybatisgenerator.model;

import java.io.Serializable;
import java.util.Date;

public class ActReDeployment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.DEPLOY_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Date deployTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String engineVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_DEPLOYMENT.PROJECT_RELEASE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String projectReleaseVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.ID_
     *
     * @return the value of ACT_RE_DEPLOYMENT.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.ID_
     *
     * @param id the value for ACT_RE_DEPLOYMENT.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.NAME_
     *
     * @return the value of ACT_RE_DEPLOYMENT.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.NAME_
     *
     * @param name the value for ACT_RE_DEPLOYMENT.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.CATEGORY_
     *
     * @return the value of ACT_RE_DEPLOYMENT.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.CATEGORY_
     *
     * @param category the value for ACT_RE_DEPLOYMENT.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.KEY_
     *
     * @return the value of ACT_RE_DEPLOYMENT.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.KEY_
     *
     * @param key the value for ACT_RE_DEPLOYMENT.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.TENANT_ID_
     *
     * @return the value of ACT_RE_DEPLOYMENT.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.TENANT_ID_
     *
     * @param tenantId the value for ACT_RE_DEPLOYMENT.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.DEPLOY_TIME_
     *
     * @return the value of ACT_RE_DEPLOYMENT.DEPLOY_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Date getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.DEPLOY_TIME_
     *
     * @param deployTime the value for ACT_RE_DEPLOYMENT.DEPLOY_TIME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.ENGINE_VERSION_
     *
     * @return the value of ACT_RE_DEPLOYMENT.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.ENGINE_VERSION_
     *
     * @param engineVersion the value for ACT_RE_DEPLOYMENT.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setEngineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.VERSION_
     *
     * @return the value of ACT_RE_DEPLOYMENT.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.VERSION_
     *
     * @param version the value for ACT_RE_DEPLOYMENT.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_DEPLOYMENT.PROJECT_RELEASE_VERSION_
     *
     * @return the value of ACT_RE_DEPLOYMENT.PROJECT_RELEASE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getProjectReleaseVersion() {
        return projectReleaseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_DEPLOYMENT.PROJECT_RELEASE_VERSION_
     *
     * @param projectReleaseVersion the value for ACT_RE_DEPLOYMENT.PROJECT_RELEASE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setProjectReleaseVersion(String projectReleaseVersion) {
        this.projectReleaseVersion = projectReleaseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", category=").append(category);
        sb.append(", key=").append(key);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deployTime=").append(deployTime);
        sb.append(", engineVersion=").append(engineVersion);
        sb.append(", version=").append(version);
        sb.append(", projectReleaseVersion=").append(projectReleaseVersion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}