package com.example.mybatisgenerator.model;

import java.io.Serializable;

public class ActReProcdef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.DEPLOYMENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String dgrmResourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.DESCRIPTION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.HAS_START_FORM_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte hasStartFormKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Byte hasGraphicalNotation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RE_PROCDEF.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String engineVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_RE_PROCDEF
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.ID_
     *
     * @return the value of ACT_RE_PROCDEF.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.ID_
     *
     * @param id the value for ACT_RE_PROCDEF.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.REV_
     *
     * @return the value of ACT_RE_PROCDEF.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.REV_
     *
     * @param rev the value for ACT_RE_PROCDEF.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.CATEGORY_
     *
     * @return the value of ACT_RE_PROCDEF.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.CATEGORY_
     *
     * @param category the value for ACT_RE_PROCDEF.CATEGORY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.NAME_
     *
     * @return the value of ACT_RE_PROCDEF.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.NAME_
     *
     * @param name the value for ACT_RE_PROCDEF.NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.KEY_
     *
     * @return the value of ACT_RE_PROCDEF.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.KEY_
     *
     * @param key the value for ACT_RE_PROCDEF.KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.VERSION_
     *
     * @return the value of ACT_RE_PROCDEF.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.VERSION_
     *
     * @param version the value for ACT_RE_PROCDEF.VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.DEPLOYMENT_ID_
     *
     * @return the value of ACT_RE_PROCDEF.DEPLOYMENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for ACT_RE_PROCDEF.DEPLOYMENT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.RESOURCE_NAME_
     *
     * @return the value of ACT_RE_PROCDEF.RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.RESOURCE_NAME_
     *
     * @param resourceName the value for ACT_RE_PROCDEF.RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_
     *
     * @return the value of ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getDgrmResourceName() {
        return dgrmResourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_
     *
     * @param dgrmResourceName the value for ACT_RE_PROCDEF.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setDgrmResourceName(String dgrmResourceName) {
        this.dgrmResourceName = dgrmResourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.DESCRIPTION_
     *
     * @return the value of ACT_RE_PROCDEF.DESCRIPTION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.DESCRIPTION_
     *
     * @param description the value for ACT_RE_PROCDEF.DESCRIPTION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.HAS_START_FORM_KEY_
     *
     * @return the value of ACT_RE_PROCDEF.HAS_START_FORM_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getHasStartFormKey() {
        return hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.HAS_START_FORM_KEY_
     *
     * @param hasStartFormKey the value for ACT_RE_PROCDEF.HAS_START_FORM_KEY_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setHasStartFormKey(Byte hasStartFormKey) {
        this.hasStartFormKey = hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_
     *
     * @return the value of ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Byte getHasGraphicalNotation() {
        return hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_
     *
     * @param hasGraphicalNotation the value for ACT_RE_PROCDEF.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setHasGraphicalNotation(Byte hasGraphicalNotation) {
        this.hasGraphicalNotation = hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.SUSPENSION_STATE_
     *
     * @return the value of ACT_RE_PROCDEF.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.SUSPENSION_STATE_
     *
     * @param suspensionState the value for ACT_RE_PROCDEF.SUSPENSION_STATE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.TENANT_ID_
     *
     * @return the value of ACT_RE_PROCDEF.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.TENANT_ID_
     *
     * @param tenantId the value for ACT_RE_PROCDEF.TENANT_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RE_PROCDEF.ENGINE_VERSION_
     *
     * @return the value of ACT_RE_PROCDEF.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RE_PROCDEF.ENGINE_VERSION_
     *
     * @param engineVersion the value for ACT_RE_PROCDEF.ENGINE_VERSION_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setEngineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_PROCDEF
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", category=").append(category);
        sb.append(", name=").append(name);
        sb.append(", key=").append(key);
        sb.append(", version=").append(version);
        sb.append(", deploymentId=").append(deploymentId);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", dgrmResourceName=").append(dgrmResourceName);
        sb.append(", description=").append(description);
        sb.append(", hasStartFormKey=").append(hasStartFormKey);
        sb.append(", hasGraphicalNotation=").append(hasGraphicalNotation);
        sb.append(", suspensionState=").append(suspensionState);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", engineVersion=").append(engineVersion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}