package com.example.mybatisgenerator.model;

import java.io.Serializable;

public class ActRuIdentitylink implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.GROUP_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.TYPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.TASK_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_RU_IDENTITYLINK.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private String procDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.ID_
     *
     * @param id the value for ACT_RU_IDENTITYLINK.ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.REV_
     *
     * @return the value of ACT_RU_IDENTITYLINK.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.REV_
     *
     * @param rev the value for ACT_RU_IDENTITYLINK.REV_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.GROUP_ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.GROUP_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.GROUP_ID_
     *
     * @param groupId the value for ACT_RU_IDENTITYLINK.GROUP_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.TYPE_
     *
     * @return the value of ACT_RU_IDENTITYLINK.TYPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.TYPE_
     *
     * @param type the value for ACT_RU_IDENTITYLINK.TYPE_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.USER_ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.USER_ID_
     *
     * @param userId the value for ACT_RU_IDENTITYLINK.USER_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.TASK_ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.TASK_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.TASK_ID_
     *
     * @param taskId the value for ACT_RU_IDENTITYLINK.TASK_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.PROC_INST_ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.PROC_INST_ID_
     *
     * @param procInstId the value for ACT_RU_IDENTITYLINK.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_RU_IDENTITYLINK.PROC_DEF_ID_
     *
     * @return the value of ACT_RU_IDENTITYLINK.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_RU_IDENTITYLINK.PROC_DEF_ID_
     *
     * @param procDefId the value for ACT_RU_IDENTITYLINK.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", groupId=").append(groupId);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", taskId=").append(taskId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}