package com.example.mybatisgenerator.dao;

import com.example.mybatisgenerator.model.ActRuIdentitylink;
import com.example.mybatisgenerator.model.ActRuIdentitylinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    long countByExample(ActRuIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByExample(ActRuIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insert(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insertSelective(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    List<ActRuIdentitylink> selectByExample(ActRuIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    ActRuIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") ActRuIdentitylink record, @Param("example") ActRuIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExample(@Param("record") ActRuIdentitylink record, @Param("example") ActRuIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKeySelective(ActRuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_IDENTITYLINK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKey(ActRuIdentitylink record);
}