package com.example.mybatisgenerator.dao;

import com.example.mybatisgenerator.model.ActReDeployment;
import com.example.mybatisgenerator.model.ActReDeploymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActReDeploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    long countByExample(ActReDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByExample(ActReDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insert(ActReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insertSelective(ActReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    List<ActReDeployment> selectByExample(ActReDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    ActReDeployment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") ActReDeployment record, @Param("example") ActReDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExample(@Param("record") ActReDeployment record, @Param("example") ActReDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKeySelective(ActReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RE_DEPLOYMENT
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKey(ActReDeployment record);
}