package com.example.mybatisgenerator.dao;

import com.example.mybatisgenerator.model.ActRuExecution;
import com.example.mybatisgenerator.model.ActRuExecutionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    long countByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insert(ActRuExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insertSelective(ActRuExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    List<ActRuExecution> selectByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    ActRuExecution selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") ActRuExecution record, @Param("example") ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExample(@Param("record") ActRuExecution record, @Param("example") ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKeySelective(ActRuExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_EXECUTION
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKey(ActRuExecution record);
}