package com.example.mybatisgenerator.dao;

import com.example.mybatisgenerator.model.ActRuTask;
import com.example.mybatisgenerator.model.ActRuTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    long countByExample(ActRuTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByExample(ActRuTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insert(ActRuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int insertSelective(ActRuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    List<ActRuTask> selectByExample(ActRuTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    ActRuTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") ActRuTask record, @Param("example") ActRuTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByExample(@Param("record") ActRuTask record, @Param("example") ActRuTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKeySelective(ActRuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_RU_TASK
     *
     * @mbg.generated Wed Jan 04 15:39:59 CST 2023
     */
    int updateByPrimaryKey(ActRuTask record);
}